const express = require('express');
const router = express.Router();
const userController = require('../controllers/userController');
const { authMiddleware, requireAdmin } = require('../middleware/authMiddleware');
router.post('/signup', userController.publicSignup);
router.use(authMiddleware, requireAdmin);
router.get('/', userController.getUsers);
router.post('/', userController.createUser);
router.patch('/:id/status', userController.toggleStatus);
router.post('/:id/reset-password', userController.resetPassword);
module.exports = router;
